spring:
  profile.active: prod
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  profiles:
    active:

server:
  error:
    include-stacktrace: never
api:
  security:
    secret: ${JWT_SECRET:123456}


#hay que usar variables de ambiente para evitar exponer la ruta, usuario, contraseña para evitar peligros
